apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- secret.yaml

namePrefix: dev-

# Images transformer
images:
  - name: nginx
    newName: nginx
    newTag: 1.21.1-alpine

# Common labels
commonLabels:
  environment: dev

configMapGenerator:
- name: default-configuration
  files:
    - nginx.conf
  literals:
    - type=default

secretGenerator:
- name: environment
  type: Opaque
  envs:
  - .env.secret

generatorOptions:
  disableNameSuffixHash: false
  labels:
    kustomize.generated.resource: "true"
  annotations:
    avp.kubernetes.io/path: "kv/data/lokalise-main/stage"
